
trigger:
  branches:
    include:
      - master
      - dev
      - qa
      - prod
      
  batch: true # no parallel builds (we have one test DB)-1

schedules:
- cron: "0 07 * * *"
  displayName: Daily build
  branches:
    include:
    - dev
  always: True

stages:
  - stage: testing
    jobs:
      - job: Build
        steps:
         - checkout: self
           fetchDepth: 10  # the depth of commits to ask Git to fetch-1

         - task: Bash@3
           inputs:
             targetType: 'inline'
             script: |
               # Write your commands here
               
               echo 'Hello world'
          
